language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.6
          env: deps=high
        - php: nightly
        - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

env:
    global:
        - deps=no

before_install:
    - composer self-update

before_script: composer install --dev

script: phpunit