services:
    AdminAuthentication:
      class: 'Pantono\Acl\AdminAuthentication'
      arguments:
        - ['Repository', 'Pantono\Acl\Entity\AdminUser']
        - @session
        - @config
    Acl:
      class: 'Pantono\Acl\Acl'
      arguments:
        - ['Repository', 'Pantono\Acl\Entity\AdminUser']
        - @session
        - @PrivilegeRegistry
        - @bootstrap
    PrivilegeRegistry:
      class: 'Pantono\Acl\PrivilegeRegistry'
commands:
  - Pantono\Acl\Command\CreateUser
  - Pantono\Acl\Command\ChangePassword
event_subscribers:
    - 'Pantono\Acl\Event\Subscriber'
forms:
  add_role:
    attributes:
      role: form
      class: add-role-form
      id: add_role_form
    fields:
      name:
        type: text
        placeholder: Enter role name here
        class: form-control
        label: Name
      parent:
        type: select
        choice_populator: Acl::getRoleList
        class: form-control
  login:
    attributes:
      role: form
      class: form-signin
    fields:
      username:
        type: email
        placeholder: Username
        class: form-control
        label:
        weight: 10
        required: true
        constraints:
          - Symfony\Component\Validator\Constraints\NotBlank
          - Symfony\Component\Validator\Constraints\Email

      password:
        type: password
        placeholder: Password
        label:
        weight: 20
        class: form-control
        required: true
        constraints:
          - Symfony\Component\Validator\Constraints\NotBlank
          - Symfony\Component\Validator\Constraints\Length:
              min: 4
              max: 20

      remember_me:
        type: checkbox
        label: Remember Me
        required: false
permissions:
  Pantono\Acl\Controller\Authentication:
    name: Authentication
    actions:
      loginAction: Login
  Pantono\Acl\Controller\Permissions:
    name: Administer Permissions
    actions:
      overviewAction: See overview of permission
      addAction: Add new permission
      editAction: Edit permission
