admin_login:
    route: '/admin/login'
    controller: 'Pantono\Acl\Controller\Authentication'
    action: 'adminLoginAction'
login:
    route: '/login'
    controller: 'Pantono\Acl\Controller\Authentication'
    action: 'loginAction'
permissions_list:
    route: '/admin/permissions'
    controller: 'Pantono\Acl\Controller\Permissions'
    action: 'overviewAction'
    admin: true
permissions_list:
    route: '/admin/permissions/add'
    controller: 'Pantono\Acl\Controller\Permissions'
    action: 'addAction'
    admin: true
permission_edit:
    route: '/admin/permissions/edit/{id}'
    controller: 'Pantono\Acl\Controller\Permissions'
    action: 'editAction'
    admin: true
    defaults:
      id: null
delete_role:
    route: '/admin/permissions/delete-role/{id}'
    controller: 'Pantono\Acl\Controller\Permissions'
    action: 'deleteRoleAction'
    admin: true
    defaults:
      id: null
add_role:
    route: '/admin/permissions/add-role'
    controller: 'Pantono\Acl\Controller\Permissions'
    action: 'addRoleAction'
    admin: true
    defaults:
      id: null
