services:
  Category:
    class: Pantono\Categories\Category
    arguments:
      - ['Repository', 'Pantono\Categories\Entity\Category']
      - @dispatcher
      - @Assets
      - @Metadata
forms:
    category:
      attributes:
        role: form
        class: category-form
      fields:
        id:
          type: hidden
        title:
          type: text
        parent:
          type: select
          choice_populator: Category::getCategoryListTree
        urlKey:
          type: text
          readonly: true
        active:
          type: checkbox
        metadata_id:
          type: hidden
        metadata_pageTitle:
          type: textarea
        metadata_metaDescription:
          type: textarea
        metadata_metaDescription:
          type: text
        metadata_metaRobots:
          type: select
        image:
          type: file
entity_mapping:
  category_add:
    entities:
      category: 'Pantono\Categories\Entity\Category'
    mapping:
      id:
        mapping: category.id
      title:
        mapping: category.title
      parent:
        mapping: category.parent.id
      urlKey:
        mapping: category.urlKey
      active:
        mapping: category.active
      metadata_id:
        mapping: category.metadata.id
      metadata_pageTitle:
        mapping: category.metadata.pageTitle
      metadata_metaDescription:
        mapping: category.metadata.metaDescription
      metadata_metaRobots:
        mapping: category.metadata.metaRobots
      image:
        mapping: category.image
