services:
  Category:
    class: Pantono\Categories\Category
    arguments:
      - ['Repository', 'Pantono\Categories\Entity\Category']
      - @dispatcher
      - @EntityHydrator
      - @Assets
forms:
    category:
      attributes:
        role: form
        class: category-form
      fields:
        id:
          type: hidden
        title:
          type: text
        parent:
          type: select
          choice_populator: Category::getCategoryListTree
        urlKey:
          type: text
          readonly: true
        active:
          type: checkbox
        image:
          type: file
