services:
  Category:
    class: Pantono\Categories\Category
    arguments:
      - ['Repository', 'Pantono\Categories\Entity\Category']
      - @dispatcher
      - @Assets
      - @Metadata
forms:
    category:
      entityMapping:
        category: 'Pantono\Categories\Entity\Category'
      attributes:
        role: form
        class: category-form
      fields:
        id:
          type: hidden
          mapping: category.id
        title:
          type: text
          mapping: category.title
        parent:
          type: select
          mapping: category.parent
          choice_populator: Category::getCategoryListTree
        urlKey:
          type: text
          mapping: category.urlKey
          readonly: true
        active:
          mapping: category.active
          type: checkbox
        metadata_id:
          type: hidden
          mapping: category.metadata.id
        metadata_pageTitle:
          type: textarea
          mapping: category.metadata.pageTitle
        metadata_metaDescription:
          type: textarea
          mapping: category.metadata.metaDescription
        metadata_metaDescription:
          type: text
          mapping: category.metadata.metaKeywords
        metadata_metaRobots:
          type: select
          mapping: category.metadata.metaRobots
        image:
          mapping: category.image
          type: file
