database:
    database_name: pantono
    username: pantono
    password: pantono
    host: localhost
    driver: pdo_mysql
debug: true
locales:
    en: locales/en.yml
    es: locales/es.yml
admin:
  session_timeout: 1800