admin:
  session_timeout: 1800
modules:
  - Pantono\Database
  - Pantono\Acl
  - Pantono\Assets
  - Pantono\Cart
  - Pantono\Categories
  - Pantono\Contacts
  - Pantono\Core
  - Pantono\Customers
  - Pantono\Form
  - Pantono\Email
  - Pantono\Orders
  - Pantono\Metadata
  - Pantono\Session
  - Pantono\Pages
  - Pantono\Payments
  - Pantono\Products
  - Pantono\Templates
  - Pantono\Suppliers
  - Pantono\Admin
  - Pantono\Locale
locale:
  locales:
    en: locales/en.yml
    es: locales/es.yml
  currencies:
    - GBP
    - USD
  numberFormat:
    - 2
    - "."
    - ","
  timezone: Europe/London
  dateFormat:
    short: d/m/Y
    long: d/m/Y H:i:s
    interval: '%d days'
