database:
    database_name: pantono
    username: pantono
    password: pantono
    host: localhost
    driver: pdo_mysql
debug: true
locales:
    en: locales/en.yml
    es: locales/es.yml
admin:
  session_timeout: 1800
modules:
  - Pantono\Database
  - Pantono\Acl
  - Pantono\Assets
  - Pantono\Cart
  - Pantono\Categories
  - Pantono\Contacts
  - Pantono\Core
  - Pantono\Customers
  - Pantono\Form
  - Pantono\Email
  - Pantono\Orders
  - Pantono\Session
  - Pantono\Pages
  - Pantono\Payments
  - Pantono\Products
  - Pantono\Templates
  - Pantono\Suppliers
  - Pantono\Admin