database:
    database_name: pantono
    username: pantono
    password: pantono
    host: localhost
    driver: pdo_mysql
debug: true
filesystems:
  private:
    adapter: 'League\Flysystem\Adapter\Local'
    args:
      - '../data'
  assets:
    adapter: 'League\Flysystem\Adapter\Local'
    args:
      - '../data/assets/'
website:
  host: pantono.dev
assets:
  css:
    minify: true
  javascript:
    minify: true