services:
  products:
    class: Pantono\Products\Products
    arguments:
      - ["Repository", "Pantono\\Products\\Entity\\Product"]
      - "@EventManager"
forms:
  product:
    attributes:
      role: form
      class: product-form
    fields:
      id:
        type: hidden
      title:
        type: text
