event_subscribers:
    - 'Pantono\Assets\Event\Subscriber'
services:
  Assets:
    class: Pantono\Assets\Assets
    arguments:
      - @public_files
      - ['Repository', 'Pantono\Assets\Entity\Asset']
      - @dispatcher
  Css:
    class: Pantono\Assets\Template\Css
    arguments:
      - @config
  Javascript:
    class: Pantono\Assets\Template\Javascript
    arguments:
      - @config